version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql80/
    environment:
      MYSQL_ROOT_PASSWORD: root
  api: 
    container_name: node
    build: 
      dockerfile: Dockerfile
      context: .
    ports: 
      - "127.0.0.1:30372:8080"
    command: 
      - nodemon
      - server.js
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development